
# XM-Sim Command File
# TOOL:	xmsim(64)	24.03-s004
#
#
# You can restore this configuration with:
#
#      xrun -f xrun_tb_dac.f -input restore.tcl
#

set tcl_prompt1 {puts -nonewline "xcelium> "}
set tcl_prompt2 {puts -nonewline "> "}
set vlog_format %h
set vhdl_format %v
set real_precision 6
set display_unit auto
set time_unit module
set heap_garbage_size -200
set heap_garbage_time 0
set assert_report_level note
set assert_stop_level error
set autoscope yes
set assert_1164_warnings yes
set pack_assert_off {}
set severity_pack_assert_off {note warning}
set assert_output_stop_level failed
set tcl_debug_level 0
set relax_path_name 1
set vhdl_vcdmap XX01ZX01X
set intovf_severity_level ERROR
set probe_screen_format 0
set rangecnst_severity_level ERROR
set textio_severity_level ERROR
set vital_timing_checks_on 1
set vlog_code_show_force 0
set assert_count_attempts 1
set tcl_all64 false
set tcl_runerror_exit false
set assert_report_incompletes 0
set show_force 1
set force_reset_by_reinvoke 0
set tcl_relaxed_literal 0
set probe_exclude_patterns {}
set probe_packed_limit 4k
set probe_unpacked_limit 16k
set assert_internal_msg no
set svseed 0
set assert_reporting_mode 0
set vcd_compact_mode 0
set vhdl_forgen_loopindex_enum_pos 0
set xmreplay_dc_debug 0
set tcl_runcmd_interrupt next_command
set tcl_sigval_prefix {#}
alias . run
alias indago verisium
alias quit exit
database -open -shm -into waves.shm waves -default
probe -create -database waves tb_dac_top.DUT.Ical tb_dac_top.DUT.Vout tb_dac_top.DUT.Voutb tb_dac_top.DUT.atb tb_dac_top.DUT.atb_ena tb_dac_top.DUT.clkin tb_dac_top.DUT.clkinb tb_dac_top.DUT.dataical tb_dac_top.DUT.datainbin tb_dac_top.DUT.datainbinb tb_dac_top.DUT.dataintherm tb_dac_top.DUT.datainthermb tb_dac_top.DUT.pdb tb_dac_top.DUT.vddana_0p8 tb_dac_top.DUT.vddana_1p8 tb_dac_top.DUT.vssana
probe -create -database waves tb_dac_top.DUT.local_bias_inst.atb0 tb_dac_top.DUT.local_bias_inst.atb1 tb_dac_top.DUT.local_bias_inst.atb_ena tb_dac_top.DUT.local_bias_inst.iclkdist_25ua tb_dac_top.DUT.local_bias_inst.icurrentsource_500ua tb_dac_top.DUT.local_bias_inst.icurrentsterring_500ua tb_dac_top.DUT.local_bias_inst.isynclatch_25ua tb_dac_top.DUT.local_bias_inst.pdb tb_dac_top.DUT.local_bias_inst.vcas tb_dac_top.DUT.local_bias_inst.vddana_0p8 tb_dac_top.DUT.local_bias_inst.vddana_1p8 tb_dac_top.DUT.local_bias_inst.vssana
probe -create -database waves tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_binary_0 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_binary_0_red tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_binary_1 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_binary_2 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_binary_3 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_binary_4 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_binary_5 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_them_0 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_them_1 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_them_2 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_them_3 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_them_4 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_them_5 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_them_6 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_them_7 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_them_8 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_them_9 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_them_10 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_them_11 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_them_12 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_them_13 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_them_14 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_them_15 tb_dac_top.DUT.CurrentSourceUnits_inst.Iout_them_16 tb_dac_top.DUT.CurrentSourceUnits_inst.atb0 tb_dac_top.DUT.CurrentSourceUnits_inst.atb1 tb_dac_top.DUT.CurrentSourceUnits_inst.atb_ena tb_dac_top.DUT.CurrentSourceUnits_inst.iref_500ua tb_dac_top.DUT.CurrentSourceUnits_inst.pdb tb_dac_top.DUT.CurrentSourceUnits_inst.vddana_0p8 tb_dac_top.DUT.CurrentSourceUnits_inst.vddana_1p8 tb_dac_top.DUT.CurrentSourceUnits_inst.vssana
probe -create -database waves tb_dac_top.DUT.currentSterring_inst.Ical tb_dac_top.DUT.currentSterring_inst.Iout tb_dac_top.DUT.currentSterring_inst.Iout_binary_0 tb_dac_top.DUT.currentSterring_inst.Iout_binary_0_red tb_dac_top.DUT.currentSterring_inst.Iout_binary_1 tb_dac_top.DUT.currentSterring_inst.Iout_binary_2 tb_dac_top.DUT.currentSterring_inst.Iout_binary_3 tb_dac_top.DUT.currentSterring_inst.Iout_binary_4 tb_dac_top.DUT.currentSterring_inst.Iout_binary_5 tb_dac_top.DUT.currentSterring_inst.Iout_them_0 tb_dac_top.DUT.currentSterring_inst.Iout_them_1 tb_dac_top.DUT.currentSterring_inst.Iout_them_2 tb_dac_top.DUT.currentSterring_inst.Iout_them_3 tb_dac_top.DUT.currentSterring_inst.Iout_them_4 tb_dac_top.DUT.currentSterring_inst.Iout_them_5 tb_dac_top.DUT.currentSterring_inst.Iout_them_6 tb_dac_top.DUT.currentSterring_inst.Iout_them_7 tb_dac_top.DUT.currentSterring_inst.Iout_them_8 tb_dac_top.DUT.currentSterring_inst.Iout_them_9 tb_dac_top.DUT.currentSterring_inst.Iout_them_10 tb_dac_top.DUT.currentSterring_inst.Iout_them_11 tb_dac_top.DUT.currentSterring_inst.Iout_them_12 tb_dac_top.DUT.currentSterring_inst.Iout_them_13 tb_dac_top.DUT.currentSterring_inst.Iout_them_14 tb_dac_top.DUT.currentSterring_inst.Iout_them_15 tb_dac_top.DUT.currentSterring_inst.Iout_them_16 tb_dac_top.DUT.currentSterring_inst.Ioutb tb_dac_top.DUT.currentSterring_inst.Vcas tb_dac_top.DUT.currentSterring_inst.atb0 tb_dac_top.DUT.currentSterring_inst.atb1 tb_dac_top.DUT.currentSterring_inst.atb_ena tb_dac_top.DUT.currentSterring_inst.dataical tb_dac_top.DUT.currentSterring_inst.datain tb_dac_top.DUT.currentSterring_inst.datainb tb_dac_top.DUT.currentSterring_inst.datatherm tb_dac_top.DUT.currentSterring_inst.datathermb tb_dac_top.DUT.currentSterring_inst.iref_500ua tb_dac_top.DUT.currentSterring_inst.pdb tb_dac_top.DUT.currentSterring_inst.vddana_0p8 tb_dac_top.DUT.currentSterring_inst.vddana_1p8 tb_dac_top.DUT.currentSterring_inst.vssana tb_dac_top.DUT.I11.Iin tb_dac_top.DUT.I11.Iinb tb_dac_top.DUT.I11.vout tb_dac_top.DUT.I11.voutb tb_dac_top.DUT.I11.vssana tb_dac_top.DUT.clock_distribution_inst.atb0 tb_dac_top.DUT.clock_distribution_inst.atb1 tb_dac_top.DUT.clock_distribution_inst.atb_ena tb_dac_top.DUT.clock_distribution_inst.clkin tb_dac_top.DUT.clock_distribution_inst.clkinb tb_dac_top.DUT.clock_distribution_inst.clkout_binary_0 tb_dac_top.DUT.clock_distribution_inst.clkout_binary_0_red tb_dac_top.DUT.clock_distribution_inst.clkout_binary_1 tb_dac_top.DUT.clock_distribution_inst.clkout_binary_2 tb_dac_top.DUT.clock_distribution_inst.clkout_binary_3 tb_dac_top.DUT.clock_distribution_inst.clkout_binary_4 tb_dac_top.DUT.clock_distribution_inst.clkout_binary_5 tb_dac_top.DUT.clock_distribution_inst.clkout_therm_0 tb_dac_top.DUT.clock_distribution_inst.clkout_therm_1 tb_dac_top.DUT.clock_distribution_inst.clkout_therm_2 tb_dac_top.DUT.clock_distribution_inst.clkout_therm_3 tb_dac_top.DUT.clock_distribution_inst.clkout_therm_4 tb_dac_top.DUT.clock_distribution_inst.clkout_therm_5 tb_dac_top.DUT.clock_distribution_inst.clkout_therm_6 tb_dac_top.DUT.clock_distribution_inst.clkout_therm_7 tb_dac_top.DUT.clock_distribution_inst.clkout_therm_8 tb_dac_top.DUT.clock_distribution_inst.clkout_therm_9 tb_dac_top.DUT.clock_distribution_inst.clkout_therm_10 tb_dac_top.DUT.clock_distribution_inst.clkout_therm_11 tb_dac_top.DUT.clock_distribution_inst.clkout_therm_12 tb_dac_top.DUT.clock_distribution_inst.clkout_therm_13 tb_dac_top.DUT.clock_distribution_inst.clkout_therm_14 tb_dac_top.DUT.clock_distribution_inst.clkout_therm_15 tb_dac_top.DUT.clock_distribution_inst.clkout_therm_16 tb_dac_top.DUT.clock_distribution_inst.clkoutb_binary_0 tb_dac_top.DUT.clock_distribution_inst.clkoutb_binary_0_red tb_dac_top.DUT.clock_distribution_inst.clkoutb_binary_1 tb_dac_top.DUT.clock_distribution_inst.clkoutb_binary_2 tb_dac_top.DUT.clock_distribution_inst.clkoutb_binary_3 tb_dac_top.DUT.clock_distribution_inst.clkoutb_binary_4 tb_dac_top.DUT.clock_distribution_inst.clkoutb_binary_5 tb_dac_top.DUT.clock_distribution_inst.clkoutb_therm_0 tb_dac_top.DUT.clock_distribution_inst.clkoutb_therm_1 tb_dac_top.DUT.clock_distribution_inst.clkoutb_therm_2 tb_dac_top.DUT.clock_distribution_inst.clkoutb_therm_3 tb_dac_top.DUT.clock_distribution_inst.clkoutb_therm_4 tb_dac_top.DUT.clock_distribution_inst.clkoutb_therm_5 tb_dac_top.DUT.clock_distribution_inst.clkoutb_therm_6 tb_dac_top.DUT.clock_distribution_inst.clkoutb_therm_7 tb_dac_top.DUT.clock_distribution_inst.clkoutb_therm_8 tb_dac_top.DUT.clock_distribution_inst.clkoutb_therm_9 tb_dac_top.DUT.clock_distribution_inst.clkoutb_therm_10 tb_dac_top.DUT.clock_distribution_inst.clkoutb_therm_11 tb_dac_top.DUT.clock_distribution_inst.clkoutb_therm_12 tb_dac_top.DUT.clock_distribution_inst.clkoutb_therm_13 tb_dac_top.DUT.clock_distribution_inst.clkoutb_therm_14 tb_dac_top.DUT.clock_distribution_inst.clkoutb_therm_15 tb_dac_top.DUT.clock_distribution_inst.clkoutb_therm_16 tb_dac_top.DUT.clock_distribution_inst.iref_25ua tb_dac_top.DUT.clock_distribution_inst.pdb tb_dac_top.DUT.clock_distribution_inst.vddana_0p8 tb_dac_top.DUT.clock_distribution_inst.vssana tb_dac_top.DUT.rsync_latch_inst.atb0 tb_dac_top.DUT.rsync_latch_inst.atb1 tb_dac_top.DUT.rsync_latch_inst.atb_ena tb_dac_top.DUT.rsync_latch_inst.clkin_binary_0 tb_dac_top.DUT.rsync_latch_inst.clkin_binary_0_red tb_dac_top.DUT.rsync_latch_inst.clkin_binary_1 tb_dac_top.DUT.rsync_latch_inst.clkin_binary_2 tb_dac_top.DUT.rsync_latch_inst.clkin_binary_3 tb_dac_top.DUT.rsync_latch_inst.clkin_binary_4 tb_dac_top.DUT.rsync_latch_inst.clkin_binary_5 tb_dac_top.DUT.rsync_latch_inst.clkin_therm_0 tb_dac_top.DUT.rsync_latch_inst.clkin_therm_1 tb_dac_top.DUT.rsync_latch_inst.clkin_therm_2 tb_dac_top.DUT.rsync_latch_inst.clkin_therm_3 tb_dac_top.DUT.rsync_latch_inst.clkin_therm_4 tb_dac_top.DUT.rsync_latch_inst.clkin_therm_5 tb_dac_top.DUT.rsync_latch_inst.clkin_therm_6 tb_dac_top.DUT.rsync_latch_inst.clkin_therm_7 tb_dac_top.DUT.rsync_latch_inst.clkin_therm_8 tb_dac_top.DUT.rsync_latch_inst.clkin_therm_9 tb_dac_top.DUT.rsync_latch_inst.clkin_therm_10 tb_dac_top.DUT.rsync_latch_inst.clkin_therm_11 tb_dac_top.DUT.rsync_latch_inst.clkin_therm_12 tb_dac_top.DUT.rsync_latch_inst.clkin_therm_13 tb_dac_top.DUT.rsync_latch_inst.clkin_therm_14 tb_dac_top.DUT.rsync_latch_inst.clkin_therm_15 tb_dac_top.DUT.rsync_latch_inst.clkin_therm_16 tb_dac_top.DUT.rsync_latch_inst.clkinb_binary_0 tb_dac_top.DUT.rsync_latch_inst.clkinb_binary_0_red tb_dac_top.DUT.rsync_latch_inst.clkinb_binary_1 tb_dac_top.DUT.rsync_latch_inst.clkinb_binary_2 tb_dac_top.DUT.rsync_latch_inst.clkinb_binary_3 tb_dac_top.DUT.rsync_latch_inst.clkinb_binary_4 tb_dac_top.DUT.rsync_latch_inst.clkinb_binary_5 tb_dac_top.DUT.rsync_latch_inst.clkinb_therm_0 tb_dac_top.DUT.rsync_latch_inst.clkinb_therm_1 tb_dac_top.DUT.rsync_latch_inst.clkinb_therm_2 tb_dac_top.DUT.rsync_latch_inst.clkinb_therm_3 tb_dac_top.DUT.rsync_latch_inst.clkinb_therm_4 tb_dac_top.DUT.rsync_latch_inst.clkinb_therm_5 tb_dac_top.DUT.rsync_latch_inst.clkinb_therm_6 tb_dac_top.DUT.rsync_latch_inst.clkinb_therm_7 tb_dac_top.DUT.rsync_latch_inst.clkinb_therm_8 tb_dac_top.DUT.rsync_latch_inst.clkinb_therm_9 tb_dac_top.DUT.rsync_latch_inst.clkinb_therm_10 tb_dac_top.DUT.rsync_latch_inst.clkinb_therm_11 tb_dac_top.DUT.rsync_latch_inst.clkinb_therm_12 tb_dac_top.DUT.rsync_latch_inst.clkinb_therm_13 tb_dac_top.DUT.rsync_latch_inst.clkinb_therm_14 tb_dac_top.DUT.rsync_latch_inst.clkinb_therm_15 tb_dac_top.DUT.rsync_latch_inst.clkinb_therm_16 tb_dac_top.DUT.rsync_latch_inst.datainbin tb_dac_top.DUT.rsync_latch_inst.datainbinb tb_dac_top.DUT.rsync_latch_inst.dataintherm tb_dac_top.DUT.rsync_latch_inst.datainthermb tb_dac_top.DUT.rsync_latch_inst.dataoutbin tb_dac_top.DUT.rsync_latch_inst.dataoutbinb tb_dac_top.DUT.rsync_latch_inst.dataouttherm tb_dac_top.DUT.rsync_latch_inst.dataoutthermb tb_dac_top.DUT.rsync_latch_inst.iref_25ua tb_dac_top.DUT.rsync_latch_inst.pdb tb_dac_top.DUT.rsync_latch_inst.vddana_0p8 tb_dac_top.DUT.rsync_latch_inst.vssana tb_dac_top.DUT.driver_cell_inst.databinout tb_dac_top.DUT.driver_cell_inst.databinoutb tb_dac_top.DUT.driver_cell_inst.datain tb_dac_top.DUT.driver_cell_inst.datainb tb_dac_top.DUT.driver_cell_inst.datatherm tb_dac_top.DUT.driver_cell_inst.datathermb tb_dac_top.DUT.driver_cell_inst.datathermout tb_dac_top.DUT.driver_cell_inst.datathermoutb tb_dac_top.DUT.driver_cell_inst.pdb tb_dac_top.DUT.driver_cell_inst.vddana_0p8 tb_dac_top.DUT.driver_cell_inst.vddana_1p8 tb_dac_top.DUT.driver_cell_inst.vssana

simvision -input restore.tcl.svcf
